test secret

diff --git a/.github/workflows/publish-and-release.yml b/.github/workflows/publish-and-release.yml
--- a/.github/workflows/publish-and-release.yml
+++ b/.github/workflows/publish-and-release.yml
@@ -131,10 +131,13 @@ jobs:
           echo "${CERTIFICATE_KEY}" | base64 -d > certificate/localhost.key
 
       - name: Build updated packages with PPK restore (PPK_STORE方式)
+        env:
+          PPK_STORE: ${{ secrets.PPK_STORE }}
         run: |
           UPDATED="${{ needs.detect-version-change.outputs.changed_packages }}"
           FILTERS=""
           echo "$PPK_STORE" | base64 -d > ppk_store.json
+          pnpm tsx ./scripts/restore-ppks.ts
 
           for pkg in $UPDATED; do
             pkg=$(echo "$pkg" | xargs)
@@ -142,18 +145,18 @@ jobs:
             CONFIG="packages/$pkg/.releaseconfig.json"
             REQUIRE_PPK=$(jq -r .requirePpk "$CONFIG")
 
-            if [ "$REQUIRE_PPK" == "true" ]; then
-              echo "Restoring ppk for $NAME..."
-              PPK_VALUE=$(jq -r --arg name "$NAME" '.[$name]' ppk_store.json)
+            # if [ "$REQUIRE_PPK" == "true" ]; then
+            #   echo "Restoring ppk for $NAME..."
+            #   PPK_VALUE=$(jq -r --arg name "$NAME" '.[$name]' ppk_store.json)
 
-              if [ "$PPK_VALUE" == "null" ] || [ -z "$PPK_VALUE" ]; then
-                echo "❌ PPK not found for $NAME"
-                exit 1
-              fi
+            #   if [ "$PPK_VALUE" == "null" ] || [ -z "$PPK_VALUE" ]; then
+            #     echo "❌ PPK not found for $NAME"
+            #     exit 1
+            #   fi
 
-              mkdir -p packages/$pkg/dist
-              echo "$PPK_VALUE" | base64 -d > packages/$pkg/dist/private.ppk
-            fi
+            #   mkdir -p packages/$pkg/dist
+            #   echo "$PPK_VALUE" | base64 -d > packages/$pkg/dist/private.ppk
+            # fi
 
             FILTERS="$FILTERS --filter $NAME..."
           done
